#!/usr/bin/env bash
# scripts/preflight.sh — local reproduction of the CI gates before `git push`.
# Generated by ~/claude-config/scripts/gen-preflight.py from the workflows below;
# every command is the one CI runs. A step this file does not cover is a step
# that can only fail remotely — when a workflow step is added, regenerate or
# add it here in the same commit. ~/.claude/hooks/pre-push-preflight.sh runs
# `--quick` before every push and blocks on failure.
#
# usage: scripts/preflight.sh [--quick]   (--quick skips the test / bench suites)
set -euo pipefail
cd "$(dirname "$0")/.."

quick=0
[[ "${1:-}" == "--quick" ]] && quick=1

step() { printf '\n\033[1;34m== %s\033[0m\n' "$*"; }
# `cargo clippy` reuses fresh `cargo check` artifacts and then lints nothing;
# touching the crate roots invalidates only this repo's fingerprints.
relint() { git ls-files | grep -E '(^|/)src/(lib|main)\.rs$' | xargs -r touch; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "missing tool: $1 ($2)" >&2; exit 1; }; }
has_toolchain() { rustup toolchain list | grep -q "^$1"; }

# Steps CI runs that this file cannot reproduce locally (they can only fail remotely):
#   - ci.yml:fix128-gpu-matrix:Install Vulkan / Mesa (Linux only — enables lavapipe software adapter) (no cargo / grep)
#   - ci.yml:fix128-gpu-matrix:Clone ALICE-ML (unconditional path dep used by src/weights.rs) (no cargo / grep)
#   - ci.yml:fix128-physics-solver-matrix:Install Vulkan / Mesa (Linux only — enables lavapipe software adapter) (no cargo / grep)
#   - ci.yml:fix128-physics-solver-matrix:Clone ALICE-ML (unconditional path dep used by src/weights.rs) (no cargo / grep)
#   - ci.yml:fix128-physics-solver-matrix:Clone ALICE-Physics (path dep required by physics-solver feature) (no cargo / grep)

need actionlint "brew install actionlint"
has_toolchain 1.92.0 || { echo "missing toolchain 1.92.0 (rustup toolchain install 1.92.0)" >&2; exit 1; }

step "ci.yml / fmt: Check formatting"
( export CARGO_TERM_COLOR="always"; cargo fmt -- --check )

step "ci.yml / actionlint: actionlint"
actionlint .github/workflows/*.yml

step "ci.yml / fix128-gpu-matrix: Strip optional path deps from Cargo.toml (CI does not need them)"
(
  export CARGO_TERM_COLOR="always"
  set -euo pipefail
  # `alice-physics` / `alice-sdf` / `alice-db` are declared as
  # `path = "../ALICE-XX", optional = true` for local
  # development. Each pulls a transitive tree of path deps
  # (alice-db → alice-zip → ...) that CI cannot reasonably
  # clone. Since `--features fix128-arithmetic` alone does
  # not activate any of these three, we strip their declarations
  # from Cargo.toml before build. The GPU matrix job is
  # scoped to fix128 tests, so this narrows the CI surface
  # rather than the tested surface.
  #
  # `sed -i.bak` is portable across BSD (macOS) and GNU (Linux).
  # Remove the three optional declaration lines.
  sed -i.bak '/^alice-physics = {/d; /^alice-sdf = {/d; /^alice-db = {/d' Cargo.toml
  # Feature entries that reference the stripped crates must
  # also go, otherwise cargo +1.92.0 will complain about unknown deps.
  sed -i.bak '/^physics = \["dep:alice-physics"/d' Cargo.toml
  sed -i.bak '/^sdf = \["dep:alice-sdf"/d' Cargo.toml
  sed -i.bak '/^db = \["dep:alice-db"/d' Cargo.toml
  sed -i.bak '/^physics-solver = /d' Cargo.toml
  rm -f Cargo.toml.bak
  echo "--- stripped Cargo.toml [dependencies] ---"
  grep -E "^(alice-|\[)" Cargo.toml || true
)

step "ci.yml / fix128-gpu-matrix: Build (fix128-arithmetic)"
( export CARGO_TERM_COLOR="always"; cargo +1.92.0 build --lib --features fix128-arithmetic )

step "ci.yml / fix128-physics-solver-matrix: Strip alice-sdf / alice-db path deps (not needed for physics-solver goldens)"
(
  export CARGO_TERM_COLOR="always"
  set -euo pipefail
  # Keep alice-physics + physics + physics-solver features. Only
  # drop alice-sdf / alice-db (unrelated to the goldens) so CI
  # does not need to clone them.
  sed -i.bak '/^alice-sdf = {/d; /^alice-db = {/d' Cargo.toml
  sed -i.bak '/^sdf = \["dep:alice-sdf"/d' Cargo.toml
  sed -i.bak '/^db = \["dep:alice-db"/d' Cargo.toml
  rm -f Cargo.toml.bak
  echo "--- stripped Cargo.toml [dependencies] ---"
  grep -E "^(alice-|\[)" Cargo.toml || true
)

step "ci.yml / fix128-physics-solver-matrix: Build (fix128-arithmetic + physics-solver)"
( export CARGO_TERM_COLOR="always"; cargo +1.92.0 build --lib --features fix128-arithmetic,physics-solver )

if [[ $quick -eq 1 ]]; then
  echo; echo "preflight --quick OK (test / bench suites skipped)"; exit 0
fi

step "ci.yml / fix128-gpu-matrix: Test — Fix128 CPU reference (always runs, no GPU dep)"
( export CARGO_TERM_COLOR="always"; cargo +1.92.0 test --lib --features fix128-arithmetic fix128::tests::fix128_gpu_ )

step "ci.yml / fix128-gpu-matrix: Test — WGSL shader source symbol coverage (always runs, no GPU dep)"
( export CARGO_TERM_COLOR="always"; cargo +1.92.0 test --lib --features fix128-arithmetic fix128::tests::wgsl_ )

step "ci.yml / fix128-gpu-matrix: Test — Fix128 GPU dispatch (all platforms — full 29 tests)"
( export CARGO_TERM_COLOR="always"; cargo +1.92.0 test --lib --features fix128-arithmetic fix128 -- --nocapture --test-threads=1 )

step "ci.yml / fix128-physics-solver-matrix: Test — physics-solver byte-exact CPU-GPU goldens (all platforms)"
( export CARGO_TERM_COLOR="always"; cargo +1.92.0 test --lib --features fix128-arithmetic,physics-solver -- --nocapture --test-threads=1 )

echo; echo "preflight OK"
